# Generated by Django 5.1.3 on 2025-02-01 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titlevid',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='titlevid',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='titlevid',
            name='img3',
        ),
        migrations.AddField(
            model_name='titlevid',
            name='clothes1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first', to='store.clothes'),
        ),
        migrations.AddField(
            model_name='titlevid',
            name='clothes2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='store.clothes'),
        ),
        migrations.AddField(
            model_name='titlevid',
            name='clothes3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three', to='store.clothes'),
        ),
    ]
