# Generated by Django 5.1.3 on 2025-01-08 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='color',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='color_connect',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.photo'),
        ),
        migrations.AddField(
            model_name='photo',
            name='color',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
