# Generated by Django 5.1.3 on 2024-12-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_favoriteitem_favorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='clothes_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='clothes_discount',
            field=models.PositiveSmallIntegerField(blank=True, help_text='процент скидки', null=True),
        ),
    ]
