# Generated by Django 5.1.3 on 2024-12-29 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_clothes_clothes_description_clothes_clothes_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='clothes_photo',
            field=models.FileField(blank=True, null=True, upload_to='clothes_img/'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
